apiVersion: "storage.k8s.io/v1"
kind: StorageClass
metadata:
  name: efs-sc
provisioner: "efs.csi.aws.com"
mountOptions: ["tls","iam"]
parameters:
  provisioningMode : "efs-ap"
  fileSystemId : {{ quote .Values.efs_id }}
  directoryPerms : "700"
  basePath : /{{ .Values.base_path }}